trigger:
branches:
include:
- feature/*
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: DockerInstaller@0
  inputs:
    dockerVersion: 'latest'

- script: |
    docker build -t playwright-docker .
  displayName: Build Docker Image

- script: |
    docker run playwright-docker
  displayName: Run Playwright Tests Inside Docker

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/results.xml'
  condition: succeededOrFailed()

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: playwright-report
    artifact: playwright-report
  condition: succeededOrFailed()