trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: Install Node.js

- script: |
    npm install
  displayName: Install Dependencies

- script: |
    npx playwright install --with-deps
  displayName: Install Playwright Browsers

- script: |
    npx playwright test --project=chrome
  displayName: Run Playwright Tests
  env:
    URL: https://naveenautomationlabs.com/opencart/
    EMAIL: prakashshailendra45@gmail.com
    PASSWORD: Jaymanti@123

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: playwright-report
    artifact: playwright-report
  condition: succeededOrFailed()